In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('customer.csv')
df.sample(5)

    age  gender   review education purchased
45   61    Male     Poor        PG       Yes
48   39  Female     Good        UG       Yes
15   75    Male     Poor        UG        No
13   57  Female  Average    School        No
27   69  Female     Poor        PG        No

In [4]:
df = pd.read_csv('customer.csv')
print(df.columns)
df = df.drop(['age','gender'],axis = 1)

Index(['age', 'gender', 'review', 'education', 'purchased'], dtype='object')

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.2)

x_train.shape, x_test.shape

((40, 2), (10, 2))

In [7]:
x_train

     review education
32  Average        UG
7      Poor    School
0   Average    School
22     Poor        PG
4   Average        UG
2      Good        PG
3      Good        PG
8   Average        UG
25     Good    School
36     Good        UG
23     Good    School
43     Poor        PG
15     Poor        UG
26     Poor        PG
37  Average        PG
41     Good        PG
46     Poor        PG
16     Poor        UG
39     Poor        PG
11     Good        UG
31     Poor    School
35     Poor    School
44  Average        UG
19     Poor        PG
5   Average    School
42     Good        PG
17     Poor        UG
18     Good    School
10     Good        UG
28     Poor    School
34  Average    School
6      Good    School
49     Good        UG
48     Good        UG
29  Average        UG
12     Poor    School
47     Good        PG
33     Good        PG
45     Poor        PG
24  Average        PG

In [10]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

x = df.drop('purchased',axis=1)

y = df['purchased']

x_train,x_test,_,_ = train_test_split(x,y,test_size=0.2,random_state=42)

categories_list = [['Poor','Average','Good'],['School','UG','PG']]

oe = OrdinalEncoder(categories=categories_list)

x_train = oe.fit_transform(x_train)
x_test =oe.transform(x_test)

In [11]:
x_train

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [12]:
x_test

array([[1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.]])

In [14]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()

In [17]:
le.fit(y_train)

LabelEncoder()

In [18]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [19]:
x_train = le.transform(y_train)
x_test = le.transform(y_test)

In [20]:
y_train

36    Yes
43     No
20    Yes
25     No
32    Yes
1      No
24    Yes
10    Yes
40     No
45    Yes
49     No
21     No
38     No
19    Yes
47    Yes
30     No
8      No
18     No
33    Yes
46     No
0      No
6      No
16    Yes
3      No
14    Yes
12     No
39     No
41    Yes
28     No
35    Yes
37    Yes
27     No
42    Yes
5     Yes
17    Yes
29    Yes
13     No
7     Yes
4      No
15     No
Name: purchased, dtype: object

In [21]:
y_test

22    Yes
48    Yes
9     Yes
31    Yes
34     No
26     No
44     No
11    Yes
23     No
2      No
Name: purchased, dtype: object